version: '3.9'

services:
  backend:
    build: ./Server
    ports:
      - '5000:5000'
    volumes:
      - ./uploads:/app/uploads
    environment:
      DB: mongodb+srv://choudharygaurav884:310886Mongodb@cluster0.yo9cuqs.mongodb.net/food-App
      NODE_ENV: development
      JWTSECRET: myNewSecret
      FRONTEND: 'http://localhost:5173'
      PORT: 5000
    depends_on:
      - mongo

  frontend:
    build: ./qr-app
    ports:
      - '5173:80'
    environment:
      VITE_BACKEND_URL: 'http://localhost:5000'
    depends_on:
      - backend

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
